/**
 * Studio dashboard copy.
 * Change any sentence here — the admin UI reads from this file only.
 * Do not change keys; only the English strings.
 */
export const ADMIN_COPY = {
  brand: {
    kicker: "Sign Up",
    studio: "Project studio",
    mobile: "Studio",
  },
  nav: {
    studio: "Studio",
    homepage: "Homepage",
    preview: "Preview",
    stats: "Statistics",
    projects: "Projects",
    addProject: "Add project",
    intro: "Intro",
    showreel: "Showreel",
    site: "View site",
    gallery: "View gallery",
    account: "Account",
    logout: "Log out",
  },
  login: {
    kicker: "Studio admin",
    title: "Welcome back",
    subtitle: "Sign in to manage the project gallery.",
    email: "Email",
    password: "Password",
    emailPlaceholder: "Email address",
    passwordPlaceholder: "Password",
    submit: "Continue",
  },
  dashboard: {
    kicker: "Overview",
    title: "Studio dashboard",
    subtitle:
      "A live snapshot of the work on Our Services. Upload into Branding, Marketing, Photo & Video, or NFC.",
    statsKicker: "Statistics",
    statsTitle: "Library at a glance",
    statsHint: "Counted from the projects already in this studio.",
    total: "Total projects",
    stills: "Still images",
    videos: "Videos",
    nfc: "NFC pieces",
    recent: "Updated this week",
    mixTitle: "Category mix",
    mixEmpty: "Upload the first project to see the mix fill in.",
    donutTitle: "Media mix",
    donutHint: "Stills versus video in the live library.",
    barTitle: "Projects by category",
    barHint: "How the work is split across Our Services.",
    openLibrary: "Open library",
    quickActions: "Quick actions",
    quickActionsHint: "Jump to the work you do most.",
    latestTitle: "Latest projects",
    latestHint: "Most recently updated in the library.",
    latestEmpty: "Upload a project to see it here.",
    viewAll: "View all",
    libraryKicker: "Library",
    libraryTitle: "Projects",
    addProject: "Add project",
    empty: "No projects in this category yet.",
    filterAll: "All",
    edit: "Edit",
  },
  project: {
    addTitle: "Add project",
    addSubtitle:
      "Name the piece, pick a category, write the story if you want, then drop the hero file and any labeled journey stills.",
    editTitle: "Edit project",
    editSubtitle:
      "Update the title, story, category, or replace files. Empty file fields keep what is live now.",
    back: "Back to projects",
    detailsKicker: "01  Details",
    detailsHint: "This title appears on Our Services and the project page.",
    titleLabel: "Title",
    titlePlaceholder: "Brand Story – 2024",
    categoryLabel: "Category",
    storyKicker: "03  Story",
    storyLabel: "Project story (optional)",
    storyHint:
      "A few lines for this project’s public journey. Leave empty to keep the default category line.",
    storyPlaceholder: "What this chapter is about — in your words.",
    storyPlaceholders: {
      brand_identity:
        "Colors, voice, the mark, and how it lives on pack, paper, and street.",
      packaging: "The pack that sits on the shelf — sizes, finish, the brand in the hand.",
      prints: "Cards, bags, and paper the brand can hold.",
      social_media: "The campaign on screens, not a pile of posts.",
      outdoors: "The brand in the street — boards, city, the real world.",
      brand_strategy: "Where you stand now, and where you want to be.",
      marketing_strategy: "Budget, time, and the mix that moves sales.",
      photos: "Still frames of the brand in the world.",
      videos: "What this film is proving.",
      nfc_card: "A card the customer can tap.",
      nfc_ring: "A ring that carries the brand.",
      nfc_medal: "A medal they can wear and tap.",
    } as Record<string, string>,
    mediaKicker: "02  Media",
    imageLabel: "Image file",
    videoLabel: "Video file",
    heroLabels: {
      brand_identity: "Logo",
      packaging: "Hero pack",
      prints: "Lead print piece",
      social_media: "Lead still",
      outdoors: "Lead board",
      brand_strategy: "Lead image",
      marketing_strategy: "Lead image",
      photos: "Hero frame",
      nfc_card: "Card — front",
      nfc_ring: "The ring",
      nfc_medal: "The medal",
    } as Record<string, string>,
    heroHints: {
      brand_identity: "The mark on its own. First frame of the journey.",
      packaging: "The main pack shot — front, clean set.",
      prints: "The print piece that opens the spread.",
      social_media: "The still that leads the phone reel.",
      outdoors: "The board in the street.",
      brand_strategy: "Image for the opening chapter.",
      marketing_strategy: "Image for the opening chapter.",
      photos: "The lead still on the strip.",
      nfc_card: "The face of the card.",
      nfc_ring: "The ring on a clean set.",
      nfc_medal: "The medal on a clean set.",
    } as Record<string, string>,
    keepFile: "Leave empty to keep the current file.",
    dropFile: "Click or drag a file here",
    imageHint: "JPG, PNG, WEBP or GIF up to 10MB",
    videoHint: "MP4, WEBM or MOV up to 200MB",
    posterLabel: "Poster image (optional)",
    posterButton: "Choose poster",
    galleryKicker: "04  Journey stills",
    galleryLabel: "Journey images (optional)",
    galleryFallback:
      "Each slot is a different frame on the public journey. Skip any you do not have.",
    galleryAdd: "Add more images",
    galleryRemove: "Remove",
    galleryMore: "More stills",
    galleryMoreHint: "Anything that does not fit a slot above. Same 12-image cap.",
    slotChoose: "Choose image",
    slotEmpty: "Optional — skip if you do not have this frame.",
    slotCaption: "Caption (optional)",
    slotCaptionPlaceholder: "What this frame is, in a short line.",
    save: "Update project",
    upload: "Create project",
    creating: "Creating…",
    updating: "Updating…",
    createdToast: "Project created successfully.",
    updatedToast: "Project updated successfully.",
    galleryHints: {
      brand_identity:
        "Hero is the logo. Optional stills: logo on a product, brand book, pack, card, street.",
      packaging: "Hero is the main pack. Add other SKUs, a label crop, in-hand, or shelf.",
      prints: "Hero is the lead print. Add a bag, letterhead, or poster.",
      social_media: "Hero is the lead still. Add a story frame or campaign visual.",
      outdoors: "Hero is the board. Add a city context or vehicle wrap.",
      photos: "Hero is the lead frame. Add a portrait, detail, or wide shot.",
      brand_strategy: "Optional images for the Now, Horizon, and Path chapters.",
      marketing_strategy: "Optional images for the Budget, Time, and Mix chapters.",
      nfc_card: "Hero is the card front. Add the back or in-hand.",
      nfc_ring: "Hero is the ring. Add it on the hand or a detail crop.",
      nfc_medal: "Hero is the medal. Add it worn or a detail crop.",
    } as Record<string, string>,
    slots: {
      logo_on_product: {
        label: "Logo on product",
        hint: "The same mark applied to a pack, bottle, or product.",
      },
      brand_book: {
        label: "Brand book",
        hint: "A spread from the guideline — type, palette, voice.",
      },
      pack: {
        label: "Pack",
        hint: "Packaging that uses this identity.",
      },
      card: {
        label: "Card / stationery",
        hint: "Business card, letterhead, or paper piece.",
      },
      street: {
        label: "Street / outdoor",
        hint: "The brand in the real world.",
      },
      sku: {
        label: "Another SKU",
        hint: "A second size or flavour in the same system.",
      },
      detail: {
        label: "Detail / label",
        hint: "Close-up of the finish, type, or label.",
      },
      in_hand: {
        label: "In the hand",
        hint: "Held, tapped, or used — not a pack shot.",
      },
      shelf: {
        label: "On the shelf",
        hint: "How it sits next to other products.",
      },
      bag: {
        label: "Bag",
        hint: "Paper bag or carrier.",
      },
      letterhead: {
        label: "Letterhead / paper",
        hint: "Stationery the brand can hold.",
      },
      poster: {
        label: "Poster / flyer",
        hint: "A printed sheet.",
      },
      story_frame: {
        label: "Story / reel still",
        hint: "A 9:16 frame as it appears on a phone.",
      },
      campaign: {
        label: "Campaign visual",
        hint: "A key visual from the campaign.",
      },
      city: {
        label: "City / context",
        hint: "The board in the neighbourhood.",
      },
      vehicle: {
        label: "Vehicle / transit",
        hint: "Wrap, bus, or street furniture.",
      },
      now: {
        label: "Where you stand",
        hint: "Image for the ‘now’ chapter.",
      },
      horizon: {
        label: "Where you want to be",
        hint: "Image for the destination chapter.",
      },
      path: {
        label: "The path",
        hint: "Image for how the work lines up.",
      },
      budget: {
        label: "Budget",
        hint: "Image for the budget chapter.",
      },
      time: {
        label: "Time",
        hint: "Image for the timeline chapter.",
      },
      mix: {
        label: "The mix",
        hint: "Image for the channel mix chapter.",
      },
      portrait: {
        label: "Portrait",
        hint: "A person or product portrait.",
      },
      wide: {
        label: "Wide / set",
        hint: "The scene around the subject.",
      },
      back: {
        label: "Card back",
        hint: "The reverse, chip, or tap mark.",
      },
      on_hand: {
        label: "On the hand",
        hint: "Worn, ready to tap.",
      },
      worn: {
        label: "Worn",
        hint: "On a person, ready to tap.",
      },
    } as Record<string, { label: string; hint: string }>,
  },
  intro: {
    title: "Intro video",
    subtitle:
      "This plays full-screen behind the home hero. Change it here and the live site updates.",
    back: "Back to dashboard",
    kicker: "Homepage",
    formTitle: "Hero background",
    formHint: "Use a short, silent loop. Visitors see this before anything else.",
    label: "Intro background video",
    extra: "MP4, WEBM or MOV up to 200MB. Leave empty to keep the current file.",
    drop: "Click or drag a video here",
    save: "Save intro video",
  },
  showreel: {
    title: "Showreel",
    subtitle: "Home page compilation video and the English / Arabic headings above it.",
    back: "Back to dashboard",
    kicker: "Homepage",
    formTitle: "Compilation + copy",
    formHint: "Swap the reel, then edit the headings the public page shows in both languages.",
    videoLabel: "Compilation video",
    videoExtra:
      "MP4, WEBM or MOV up to 200MB. This is the home showreel — use a cut of real work, not the intro clip. Leave empty to keep the current file.",
    drop: "Click or drag a compilation video here",
    copyKicker: "Text on the page",
    copyHint: "These four lines are live site copy. Change them here anytime.",
    eyebrowEn: "Eyebrow (English)",
    eyebrowAr: "Eyebrow (Arabic)",
    titleEn: "Title (English)",
    titleAr: "Title (Arabic)",
    save: "Save showreel",
  },
  account: {
    kicker: "Settings",
    title: "Account",
    subtitle: "Update the login email. Leave password blank to keep the current one.",
    email: "Email",
    password: "New password",
    confirm: "Confirm password",
    emailPlaceholder: "Email address",
    passwordPlaceholder: "Optional",
    confirmPlaceholder: "Repeat new password",
    save: "Save changes",
  },
};
